<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name_en' => 'Cardboard Sugary',
                'name_ar' => 'كرتون سكري',
                'sku' => 'CB-SUG-001',
                'barcode' => '1901992267401',
                'description_en' => 'High quality cardboard for printing',
                'description_ar' => 'كرتون عالي الجودة للطباعة',
                'type' => 'roll',
                'grammage' => 350,
                'quality' => 'standard',
                'roll_number' => 'B12',
                'source' => 'China',
                'length' => null,
                'width' => 120.00,
                'thickness' => 0.35,
                'purchase_price' => 700.00,
                'selling_price' => 750.00,
                'wholesale_price' => 720.00,
                'material_cost_per_ton' => 700.00,
                'min_stock_level' => 5,
                'max_stock_level' => 50,
                'unit' => 'kg',
                'weight' => 22350.00,
                'reserved_weight' => 0.00,
                'is_active' => true,
                'track_inventory' => true,
                'category_id' => 1,
                'supplier_id' => 1,
                // New warehouse tracking fields
                'purchase_invoice_number' => 'INV-2025-001',
                'available_weight_kg' => 22350.00,
            ],
            [
                'name_en' => 'Classic Cardboard',
                'name_ar' => 'كرتون كلاسيكي',
                'sku' => 'CB-CLS-002',
                'barcode' => '8806095072345',
                'description_en' => 'Standard quality cardboard',
                'description_ar' => 'كرتون جودة قياسية',
                'type' => 'digma',
                'grammage' => 120,
                'quality' => 'stock',
                'roll_number' => 'C25',
                'source' => 'Holland',
                'length' => 70.00,
                'width' => 100.00,
                'thickness' => 0.12,
                'purchase_price' => 550.00,
                'selling_price' => 600.00,
                'wholesale_price' => 575.00,
                'material_cost_per_ton' => 550.00,
                'min_stock_level' => 10,
                'max_stock_level' => 100,
                'unit' => 'kg',
                'weight' => 36584.00,
                'reserved_weight' => 0.00,
                'is_active' => true,
                'track_inventory' => true,
                'category_id' => 1,
                'supplier_id' => 1,
                // New warehouse tracking fields
                'purchase_invoice_number' => 'INV-2025-002',
                'available_weight_kg' => 36584.00,
            ],
            [
                'name_en' => 'Battal Cardboard',
                'name_ar' => 'كرتون بتال',
                'sku' => 'CB-BAT-003',
                'barcode' => '1234567890123',
                'description_en' => 'Large size cardboard sheets',
                'description_ar' => 'كرتون حجم كبير',
                'type' => 'bale',
                'grammage' => 110,
                'quality' => 'stock',
                'roll_number' => null,
                'source' => 'Spain',
                'length' => 90.00,
                'width' => 120.00,
                'thickness' => 0.11,
                'purchase_price' => 500.00,
                'selling_price' => 550.00,
                'wholesale_price' => 525.00,
                'material_cost_per_ton' => 500.00,
                'min_stock_level' => 20,
                'max_stock_level' => 200,
                'unit' => 'kg',
                'weight' => 598321.00,
                'reserved_weight' => 0.00,
                'is_active' => true,
                'track_inventory' => true,
                'category_id' => 1,
                'supplier_id' => 2,
                // New warehouse tracking fields
                'purchase_invoice_number' => 'INV-2025-003',
                'available_weight_kg' => 598321.00,
            ],
            [
                'name_en' => 'Gray Cardboard',
                'name_ar' => 'كرتون رمادي',
                'sku' => 'CB-GRY-004',
                'barcode' => '4567891234567',
                'description_en' => 'Gray colored cardboard',
                'description_ar' => 'كرتون لون رمادي',
                'type' => 'roll',
                'grammage' => 230,
                'quality' => 'standard',
                'roll_number' => 'O2',
                'source' => 'Internal',
                'length' => null,
                'width' => 200.00,
                'thickness' => 0.23,
                'purchase_price' => 900.00,
                'selling_price' => 950.00,
                'wholesale_price' => 925.00,
                'material_cost_per_ton' => 900.00,
                'min_stock_level' => 3,
                'max_stock_level' => 30,
                'unit' => 'kg',
                'weight' => 4791.00,
                'reserved_weight' => 0.00,
                'is_active' => true,
                'track_inventory' => true,
                'category_id' => 1,
                'supplier_id' => 3,
                // New warehouse tracking fields
                'purchase_invoice_number' => 'INV-2025-004',
                'available_weight_kg' => 4791.00,
            ],
            [
                'name_en' => 'Duplex Cardboard',
                'name_ar' => 'كرتون دوبلكس',
                'sku' => 'CB-DPX-005',
                'barcode' => '7891234567890',
                'description_en' => 'High quality duplex cardboard',
                'description_ar' => 'كرتون دوبلكس عالي الجودة',
                'type' => 'roll',
                'grammage' => 450,
                'quality' => 'standard',
                'roll_number' => 'UI23',
                'source' => 'Internal',
                'length' => null,
                'width' => 65.00,
                'thickness' => 0.45,
                'purchase_price' => 1200.00,
                'selling_price' => 1250.00,
                'wholesale_price' => 1225.00,
                'material_cost_per_ton' => 1200.00,
                'min_stock_level' => 2,
                'max_stock_level' => 20,
                'unit' => 'kg',
                'weight' => 5966.00,
                'reserved_weight' => 0.00,
                'is_active' => true,
                'track_inventory' => true,
                'category_id' => 1,
                'supplier_id' => 3,
                // New warehouse tracking fields
                'purchase_invoice_number' => 'INV-2025-005',
                'available_weight_kg' => 5966.00,
            ],
        ];

        foreach ($products as $product) {
            \App\Models\Product::create($product);
        }
    }
}
