#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           LARAVEL USER MANAGEMENT COMMANDS                   ║"
echo "║              Safe Password Reset & User Creation            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "🔧 COMMON USER MANAGEMENT TASKS:"
echo "═══════════════════════════════════"
echo ""

echo "1️⃣  RESET USER PASSWORD (Use this for admin access):"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "$user = App\\Models\\User::where('username', 'مدير_شامل')->first();"
echo "\$user->update(['password' => Hash::make('your_new_password_here')]);"
echo "exit()"
echo ""

echo "2️⃣  CREATE NEW ADMIN USER:"
echo "───────────────────────────────────────────────────"
echo "php artisan make:filament-user"
echo "# Follow the prompts to create a new user"
echo ""

echo "3️⃣  CHECK USER EXISTS AND GET INFO:"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "\$user = App\\Models\\User::where('username', 'مدير_شامل')->first();"
echo "dd(\$user);"
echo "exit()"
echo ""

echo "4️⃣  ASSIGN ROLE TO USER:"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "\$user = App\\Models\\User::where('username', 'username_here')->first();"
echo "\$user->assignRole('role_name_here');"
echo "exit()"
echo ""

echo "5️⃣  LIST ALL USERS WITH ROLES:"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "App\\Models\\User::with('roles')->get()->pluck('username', 'name', 'roles.name');"
echo "exit()"
echo ""

echo "6️⃣  CREATE USER VIA LARAVEL FACTORY (PROGRAMMATIC):"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "use App\\Models\\User;"
echo "use Illuminate\\Support\\Facades\\Hash;"
echo ""
echo "// Create user"
echo "\$user = User::create(["
echo "    'name' => 'New User Name',"
echo "    'username' => 'new_user_username',"
echo "    'email' => 'user@example.com',"
echo "    'password' => Hash::make('password123'),"
echo "    'email_verified_at' => now()"
echo "]);"
echo ""
echo "// Assign role"
echo "\$user->assignRole('موظف_مبيعات');"
echo "exit()"
echo ""

echo "7️⃣  RESET ALL ADMIN PASSWORDS (EMERGENCY):"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "\$adminUsers = App\\Models\\User::role('مدير_شامل')->get();"
echo "foreach(\$adminUsers as \$user) {"
echo "    \$user->update(['password' => Hash::make('admin123')]);"
echo "    echo 'Password reset for: ' . \$user->username . PHP_EOL;"
echo "}"
echo "exit()"
echo ""

echo "8️⃣  CHECK FILAMENT AUTH CONFIG:"
echo "───────────────────────────────────────────────────"
echo "php artisan tinker"
echo "echo 'Filament Guard: ' . config('filament.auth.guard') . PHP_EOL;"
echo "echo 'Filament Model: ' . config('filament.auth.model') . PHP_EOL;"
echo "exit()"
echo ""

echo "⚠️  IMPORTANT SECURITY NOTES:"
echo "═══════════════════════════════════"
echo "• ALWAYS change default passwords"
echo "• Use strong passwords (8+ chars, mixed case, numbers, symbols)"
echo "• Never commit passwords to version control"
echo "• Use environment variables for sensitive data"
echo "• Enable 2FA if available"
echo ""

echo "🛡️  PASSWORD STRENGTH REQUIREMENTS:"
echo "═══════════════════════════════════"
echo "• Minimum 8 characters"
echo "• At least one uppercase letter"
echo "• At least one lowercase letter"
echo "• At least one number"
echo "• At least one special character (!@#$%^&*(),.?\":{}|<>)"
echo ""

echo "📋 QUICK COMMANDS CHEAT SHEET:"
echo "═══════════════════════════════════"
echo "# Reset password for main admin:"
echo "php artisan tinker -c \"\\\$u = App\\\\Models\\\\User::where('username','مدير_شامل')->first(); \\\$u->update(['password' => Hash::make('NewPassword123!')]);\""
echo ""
echo "# Create test user quickly:"
echo "php artisan tinker -c \"\\\$u = User::create(['name'=>'Test User','username'=>'testuser','email'=>'test@test.com','password'=>Hash::make('password123'),'email_verified_at'=>now()]);\\\$u->assignRole('موظف_مبيعات');\""
echo ""

echo "✅ READY TO USE - Copy and paste commands as needed!"